namespace DeployBox.Orchestrator.Services;

public interface IDockerfileGeneratorService
{
    /// <summary>
    /// Ensures a Dockerfile exists at the root of <paramref name="sourcePath"/>.
    /// If one is already present, it is left untouched (the user's own
    /// Dockerfile always wins). Otherwise the project is auto-detected
    /// (Node.js, Python, .NET, or static HTML) and a Dockerfile is generated
    /// so users don't need to know Docker to deploy.
    /// </summary>
    /// <returns>true if a Dockerfile was generated, false if one already existed.</returns>
    bool EnsureDockerfile(string sourcePath, int containerPort);
}

public class DockerfileGeneratorService : IDockerfileGeneratorService
{
    public bool EnsureDockerfile(string sourcePath, int containerPort)
    {
        var dockerfilePath = Path.Combine(sourcePath, "Dockerfile");
        if (File.Exists(dockerfilePath))
        {
            return false;
        }

        var dockerfile = DetectAndGenerate(sourcePath, containerPort)
            ?? throw new InvalidOperationException(
                "Could not detect your project type to auto-generate a Dockerfile. " +
                "Supported: Node.js (package.json), Python (requirements.txt/pyproject.toml), " +
                ".NET (a .csproj/.sln file), or static HTML (index.html). " +
                "Add one of these files, or include your own Dockerfile in the repository root.");

        File.WriteAllText(dockerfilePath, dockerfile);
        return true;
    }

    private static string? DetectAndGenerate(string sourcePath, int containerPort)
    {
        // Order matters: a repo could contain multiple marker files (e.g. a
        // Python backend with a bundled static `index.html`) — check the
        // most specific/likely-intended stack first.
        if (File.Exists(Path.Combine(sourcePath, "package.json")))
        {
            return GenerateNodeDockerfile(sourcePath, containerPort);
        }

        var csproj = Directory.GetFiles(sourcePath, "*.csproj", SearchOption.TopDirectoryOnly)
            .Concat(Directory.GetFiles(sourcePath, "*.sln", SearchOption.TopDirectoryOnly))
            .FirstOrDefault();
        if (csproj != null)
        {
            return GenerateDotnetDockerfile(sourcePath, csproj, containerPort);
        }

        if (File.Exists(Path.Combine(sourcePath, "requirements.txt")) ||
            File.Exists(Path.Combine(sourcePath, "pyproject.toml")))
        {
            return GeneratePythonDockerfile(sourcePath, containerPort);
        }

        if (File.Exists(Path.Combine(sourcePath, "index.html")))
        {
            return GenerateStaticHtmlDockerfile(containerPort);
        }

        return null;
    }

    private static string GenerateNodeDockerfile(string sourcePath, int containerPort)
    {
        var packageJson = File.ReadAllText(Path.Combine(sourcePath, "package.json"));
        var hasBuildScript = packageJson.Contains("\"build\"");
        var hasStartScript = packageJson.Contains("\"start\"");

        var lockFile = File.Exists(Path.Combine(sourcePath, "package-lock.json")) ? "npm-lock"
            : File.Exists(Path.Combine(sourcePath, "pnpm-lock.yaml")) ? "pnpm-lock"
            : File.Exists(Path.Combine(sourcePath, "yarn.lock")) ? "yarn-lock"
            : "none";

        // `npm ci`/`--frozen-lockfile` require the lockfile to be perfectly in
        // sync with package.json; a lockfile generated by a different package
        // manager version, or one the author forgot to re-commit after adding
        // a dependency, makes them fail outright with no way to recover. Most
        // hosting platforms (Vercel, Netlify, etc.) fall back to a regular
        // install in that case rather than hard-failing the whole deploy, so
        // we do the same and say so plainly in the build log.
        var (installCmd, runner) = lockFile switch
        {
            "pnpm-lock" => ("RUN corepack enable && (pnpm install --frozen-lockfile || (echo 'pnpm-lock.yaml is out of sync with package.json — falling back to a regular install.' && pnpm install))", "pnpm"),
            "yarn-lock" => ("RUN corepack enable && (yarn install --frozen-lockfile || (echo 'yarn.lock is out of sync with package.json — falling back to a regular install.' && yarn install))", "yarn"),
            "npm-lock" => ("RUN npm ci || (echo 'package-lock.json is out of sync with package.json — falling back to npm install.' && npm install)", "npm"),
            _ => ("RUN npm install", "npm"),
        };

        var buildStep = hasBuildScript ? $"RUN {runner} run build\n" : "";

        // Projects with a build step but no `start` script (Vite/CRA/plain
        // static SPAs) have nothing that serves the built output — `npm run
        // dev` would start a dev server, which is wrong for production. Serve
        // the conventional build output directory as static files instead.
        string startCmd;
        if (hasStartScript)
        {
            startCmd = runner == "npm" ? "npm run start" : $"{runner} start";
        }
        else if (hasBuildScript)
        {
            var outDir = Directory.Exists(Path.Combine(sourcePath, "dist")) ? "dist"
                : Directory.Exists(Path.Combine(sourcePath, "build")) ? "build"
                : "dist"; // Vite's default; most common for repos without a start script.
            return $"""
                FROM node:20-alpine AS build
                WORKDIR /app
                COPY package*.json pnpm-lock.yaml* yarn.lock* ./
                {installCmd}
                COPY . .
                {buildStep}
                FROM node:20-alpine
                WORKDIR /app
                RUN npm install -g serve
                COPY --from=build /app/{outDir} ./{outDir}
                EXPOSE {containerPort}
                CMD ["serve", "-s", "{outDir}", "-l", "{containerPort}"]
                """;
        }
        else
        {
            startCmd = runner == "npm" ? "npm run dev" : $"{runner} dev";
        }

        return $"""
            FROM node:20-alpine
            WORKDIR /app
            COPY package*.json pnpm-lock.yaml* yarn.lock* ./
            {installCmd}
            COPY . .
            {buildStep}EXPOSE {containerPort}
            ENV PORT={containerPort}
            CMD [{string.Join(", ", SplitCommand(startCmd))}]
            """;
    }

    private static string GenerateDotnetDockerfile(string sourcePath, string projectFile, int containerPort)
    {
        var relativeProjectFile = Path.GetFileName(projectFile);
        var isSolution = relativeProjectFile.EndsWith(".sln");
        var publishTarget = isSolution ? "." : relativeProjectFile;

        // For a .sln target, the published .dll's name doesn't necessarily
        // match the solution's name (it matches whichever project the .sln
        // designates as the startup/only executable project), so it can't be
        // known at generation time. Resolve it at container start instead:
        // exactly one *.dll should exist directly under /app/publish for a
        // single deployable web project.
        var entrypoint = isSolution
            ? """ENTRYPOINT ["/bin/sh", "-c", "exec dotnet \"$(find /app -maxdepth 1 -name '*.dll' | head -n 1)\""]"""
            : $"""ENTRYPOINT ["dotnet", "{Path.GetFileNameWithoutExtension(relativeProjectFile)}.dll"]""";

        return $"""
            FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
            WORKDIR /src
            COPY . .
            RUN dotnet restore "{publishTarget}"
            RUN dotnet publish "{publishTarget}" -c Release -o /app/publish

            FROM mcr.microsoft.com/dotnet/aspnet:10.0
            WORKDIR /app
            COPY --from=build /app/publish .
            EXPOSE {containerPort}
            ENV ASPNETCORE_URLS=http://+:{containerPort}
            {entrypoint}
            """;
    }

    private static string GeneratePythonDockerfile(string sourcePath, int containerPort)
    {
        var hasRequirementsTxt = File.Exists(Path.Combine(sourcePath, "requirements.txt"));

        var installStep = hasRequirementsTxt
            ? "COPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt"
            : "COPY pyproject.toml* poetry.lock* ./\nRUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root";

        // Best-effort entrypoint detection for the most common frameworks;
        // users with an unusual layout can always drop in their own Dockerfile.
        var entrypoint = File.Exists(Path.Combine(sourcePath, "manage.py"))
            ? $"CMD [\"python\", \"manage.py\", \"runserver\", \"0.0.0.0:{containerPort}\"]"
            : File.Exists(Path.Combine(sourcePath, "app.py"))
                ? $"CMD [\"python\", \"app.py\"]"
                : File.Exists(Path.Combine(sourcePath, "main.py"))
                    ? $"CMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"{containerPort}\"]"
                    : $"CMD [\"python\", \"app.py\"]";

        return $"""
            FROM python:3.12-slim
            WORKDIR /app
            {installStep}
            COPY . .
            EXPOSE {containerPort}
            ENV PORT={containerPort}
            {entrypoint}
            """;
    }

    private static string GenerateStaticHtmlDockerfile(int containerPort)
    {
        return $"""
            FROM nginx:alpine
            COPY . /usr/share/nginx/html
            RUN sed -i 's/listen\\s*80;/listen {containerPort};/' /etc/nginx/conf.d/default.conf
            EXPOSE {containerPort}
            CMD ["nginx", "-g", "daemon off;"]
            """;
    }

    private static IEnumerable<string> SplitCommand(string command) =>
        command.Split(' ', StringSplitOptions.RemoveEmptyEntries).Select(part => $"\"{part}\"");
}
